### ISSUE TITLE
Better screenshot

### ISSUE THREAD

**Issue by hrach** [milo/vendor-versions#1]
The current schreenshot seems to use very very old version of Windows. We be great, if it could be updated.  Moreover, this library is about versioning and about being up-to-date, so, up-to-date version of Windows would be very nice. :wink: 

If the OS is not a Windows, then I suggest upgrading your OS, since imitating the "Windows XP's" appearance is not a good idea :smile_cat:

**Comment by OndroNR** [comment]
Looks like Vista/Win7 theme to me :)

**Comment by milo** [comment]
Guys, this is the maximum I can do for you. I will not reinstall my super-tuned-up Win7 due to screenshot ;) If you want, make one for me. On it must be:
- nette components
- Tester
- and some package in dev-master stability

**Comment by hrach** [comment]
great support, much tasty! thanks!
