### ISSUE TITLE
Rely on Ocramius/PackageVersions

### ISSUE THREAD

**Issue by Majkl578** [milo/vendor-versions#5]
I'd suggest to leverage [Ocramius/PackageVersions](https://github.com/Ocramius/PackageVersions) instead of reinventing wheel again. It's well-tested library used i.e. by Doctrine or PHPStan.

**Comment by milo** [comment]
Well, Ocramius was one week slower. Say it to him :-D

**Comment by Majkl578** [comment]
That's not really a good reason to reject though.

**Comment by milo** [comment]
Sorry, but this little tool will not depend on another package. If you want, fork it.

**Comment by JanTvrdik** [comment]
> It's well-tested library used i.e. by Doctrine or PHPStan.

My experience is quite the opposite. The overall design of Ocramius/PackageVersions is terrible, because it's a Composer plugin. And Composer plugin in my eyes === Composer virus. It's a path to hell.
