### ISSUE TITLE
compability with Tracy 2.5

### ISSUE THREAD

**Issue by petrparolek** [milo/vendor-versions#6]
Nefunguje scrolování, když není panel odepnutý a když je odepnutý, tak by měla zůstat viditelná hlavičkla tabulky

**Comment by milo** [comment]
Thanks for report. Scrolling fixed in [v1.1.4](https://github.com/milo/vendor-versions/releases/tag/v1.1.4). 

Ad. to fixed table header... I don't know any easy way to achive this.
